### ISSUE TITLE
A label added by a bot action doesn't trigger

### ISSUE THREAD

**Issue by ecureuill** [srggrs/assign-one-project-github-action#45]
I have this condition that triggers when I manually add a label to the issue. 
But when the label is added by a bot from another action, it  doesn't work. 

Is this the expected behavior?

```yml
   if: contains(github.event.issue.labels.*.name, '1 - Planning')
```

**Comment by srggrs** [comment]
mmmm not sure about the bot... I need to test it!

few questions:

1. which bot are u using for labels?
2. how your workflow file looks like (not interested in the private details, but on the instructions, see example below)
```yaml
on:
  issues:
    types: [opened, labeled]
```
3. are u sure your `label == '1 - Planning'`, I think spaces and capital letters matter.

**Comment by ecureuill** [comment]
> 3. are u sure your `label == '1 - Planning'`, I think spaces and capital letters matter.
Yes, it is working when I manually labeled a issue

I'm using the [Auto card labeler](https://github.com/marketplace/actions/auto-card-labeler) to label issues when it's moved in project. 

I found this [GITHUB_TOKEN prevent actions to trigger another action](https://help.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token), so I'm using a personal token to try to trigger your action, but no success.

Even tried to put everything together.

```yml
on:
  issues:
    types: [labeled]
  project_card:
    types: [moved]
env:
  GITHUB_TOKEN: ${{ secrets.MY_ACTION_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  triage: #GitHub actions that automatically labels Issues or PullRequests based on project card moves
    if: github.event_name == 'project_card'
    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-card-labeler@v1

  assign_one_project:
    needs: triage
 #   if: github.event_name != 'project_card' 
    runs-on: ubuntu-latest
    name: AssignToProject
    steps:
     - name: Assign 'FEATURE REQUEST' to 'TRIAGE - FEATURE REQUEST'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: contains(github.event.issue.labels.*.name, 'feature request')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/3'
        column_name: 'NEEDS TRIAGE'
```
