### ISSUE TITLE
project not found

### ISSUE THREAD

**Issue by GRBurst** [srggrs/assign-one-project-github-action#46]
Hey there :wave: and thanks for this amazing action.

Sadly, I am getting this error when running this action:
```
Run srggrs/assign-one-project-github-action@1.2.0
/usr/bin/docker run --name srggrsassignoneprojectgithubaction120_2c2dc5 --label c27d31 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_PROJECT -e INPUT_COLUMN_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/[org/repo/repo]":"/github/workspace" srggrs/assign-one-project-github-action:1.2.0  "https://github.com/[org/repo]/projects/1" ""
jq: error (at <stdin>:4): Cannot index string with string "html_url"
No project was found.
jq: error (at <stdin>:4): Cannot index string with string "name"
INITIAL_COLUMN_ID is not found.
```

I have no other actions in the repo defined. I c&p your example, so my action looks like this:
```
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GithubToken }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign NEW issues and NEW pull requests to [project] project (project 1)
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/[org/project]/projects/1'
```

Trying to use `column_name` without a value gives the same error and further an error is shown in the github ui when editing the action.

Note: I used `[]` for placeholders for real values, e.g. in the project url ;-)
