### ISSUE TITLE
Move a PR/Issue to another column

### ISSUE THREAD

**Issue by ran-huang** [srggrs/assign-one-project-github-action#48]
Hi, thank you for this great GitHub Action! 😀

I try to use this action to move a PR to another column when a label is deleted. However, it couldn't work and give this error message. 

Is this a bug or unsupported feature?

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "ProjectCard",
      "code": "unprocessable",
      "field": "data",
      "message": "Project already has the associated issue"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/projects/cards/#create-a-project-card"
}
```

**Comment by srggrs** [comment]
mmmm not sure it supports moving to another column when the label is removed, perhaps a workflow like this might work:
```yaml
on:
  pull_request:
    types: [unlabeled]
...
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/srggrs/assign-one-project-github-action/projects/XXXX'
        column_name: 'Not Labeled PRs'
```
see https://help.github.com/en/actions/reference/events-that-trigger-workflows for all the events that trigger the action
