### ISSUE TITLE
Help: Cannot add project into new pull request

### ISSUE THREAD

**Issue by zigang93** [srggrs/assign-one-project-github-action#57]
I was able to add project into the issue. 
but not working on fork pull request.
Am I doing something wrong??

P/S: my orgs repo is private and the fork repo also private

```yaml
name: Auto PR/Issue Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/example/projects/5'
        column_name: 'To Do'
    
    - name: Assign NEW PR to project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        github.event == 'pull_request' &&
        (
          github.event.action == 'opened'
        )
      with:
        project: 'https://github.com/orgs/example/projects/5'
        column_name: 'In Progress'
```
