### ISSUE TITLE
MY_GITHUB_TOKEN not defined

### ISSUE THREAD

**Issue by l3alr0g** [srggrs/assign-one-project-github-action#70]
I have been trying to automate the process of assigning issues to an organization project from a repository, here's my main.yml : 
```yml
name: Auto Assign to Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project Global Feature progress
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/7map/projects/1'
        column_name: 'To do'
```
I have created a personal token for the organization (from my user settings) and added it to the repository secrets but every time I run the job, it fails with a `MY_GITHUB_TOKEN not defined` error message.
Some help would be greatly appreciated 😄
