### ISSUE TITLE
Support for just the project_number

### ISSUE THREAD

**Issue by woodie** [srggrs/assign-one-project-github-action#71]
We should have `$GITHUB_SERVER_URL` and `$GITHUB_REPOSITORY` in the environment. Any chance we can make this more portable by accepting a project number?

```yml
jobs:
  add-new-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project_number: 1
 ```

**Comment by woodie** [comment]
Actually, this works just fine as well.

```yml
name: Add new issues to project board

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-new-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/${{ github.repository }}/projects/1'

```
