### ISSUE TITLE
Include minimum permission needs in README.md

### ISSUE THREAD

**Issue by Bekreth** [srggrs/assign-one-project-github-action#72]
Given that this project can use the `GITHUB_TOKEN`, I think the README should include the minimum necessary permissions for the actions to run successfully.  Something like this
```yaml
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: write
  packages: none
  pull-requests: write
  repository-projects: write
  security-events: none
  statuses: none
```

(assuming this is the correct minimum permissions filter for the operation of the action)
