### ISSUE TITLE
INITIAL_COLUMN_ID is not found

### ISSUE THREAD

**Issue by equinusocio** [srggrs/assign-one-project-github-action#79]
I get this error while running the workflow.

```
 /usr/bin/docker run --name c9e03634bd76b72f7e4bca8e4547cecee59639_533e14 --label c9e036 --workdir /github/workspace --rm -e MY_GITHUB_TOKEN -e INPUT_PROJECT -e INPUT_COLUMN_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/design/design":"/github/workspace" c9e036:34bd76b72f7e4bca8e4547cecee59639  "https://github.com/orgs/wonderflow-bv/projects/1" "Backlog"

INITIAL_COLUMN_ID is not found.
```

I tried both `GITHUB_TOKEN` and a custom token but i get the same result. Here my config:

```yml
name: Auto Assign to Projects

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to Wanda project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/orgs/wonderflow-bv/projects/1"
          column_name: "Backlog"
```

**Comment by equinusocio** [comment]
Yes. It was the column name. I think the error message can be misleading

**Comment by brandonh-msft** [comment]
Same problem here. Proj board:
![image](https://user-images.githubusercontent.com/20270743/191360118-2768e299-d612-46e2-93d4-68e25ecc1092.png)

Workflow def:

```yaml
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to UA Project
    steps:
    - uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/dotnet/projects/xxx'
        column_name: 'Dev In Progress'
```

Does this action work on _private_ projects?
